In [ ]:
# This file was produced by the NASA Exoplanet Archive  http://exoplanetarchive.ipac.caltech.edu
# Tue Nov 25 16:37:59 2025
#
# COLUMN pl_name:        Planet Name
# COLUMN hostname:       Host Name
# COLUMN default_flag:   Default Parameter Set
# COLUMN sy_snum:        Number of Stars
# COLUMN sy_pnum:        Number of Planets
# COLUMN discoverymethod: Discovery Method
# COLUMN disc_year:      Discovery Year
# COLUMN disc_facility:  Discovery Facility
# COLUMN soltype:        Solution Type
# COLUMN pl_controv_flag: Controversial Flag
# COLUMN pl_refname:     Planetary Parameter Reference
# COLUMN pl_orbper:      Orbital Period [days]
# COLUMN pl_orbpererr1:  Orbital Period Upper Unc. [days]
# COLUMN pl_orbpererr2:  Orbital Period Lower Unc. [days]
# COLUMN pl_orbperlim:   Orbital Period Limit Flag
# COLUMN pl_orbsmax:     Orbit Semi-Major Axis [au]
# COLUMN pl_orbsmaxerr1: Orbit Semi-Major Axis Upper Unc. [au]
# COLUMN pl_orbsmaxerr2: Orbit Semi-Major Axis Lower Unc. [au]
# COLUMN pl_orbsmaxlim:  Orbit Semi-Major Axis Limit Flag
# COLUMN pl_rade:        Planet Radius [Earth Radius]
# COLUMN pl_radeerr1:    Planet Radius Upper Unc. [Earth Radius]
# COLUMN pl_radeerr2:    Planet Radius Lower Unc. [Earth Radius]
# COLUMN pl_radelim:     Planet Radius Limit Flag
# COLUMN pl_radj:        Planet Radius [Jupiter Radius]
# COLUMN pl_radjerr1:    Planet Radius Upper Unc. [Jupiter Radius]
# COLUMN pl_radjerr2:    Planet Radius Lower Unc. [Jupiter Radius]
# COLUMN pl_radjlim:     Planet Radius Limit Flag
# COLUMN pl_bmasse:      Planet Mass or Mass*sin(i) [Earth Mass]
# COLUMN pl_bmasseerr1:  Planet Mass or Mass*sin(i) [Earth Mass] Upper Unc.
# COLUMN pl_bmasseerr2:  Planet Mass or Mass*sin(i) [Earth Mass] Lower Unc.
# COLUMN pl_bmasselim:   Planet Mass or Mass*sin(i) [Earth Mass] Limit Flag
# COLUMN pl_bmassj:      Planet Mass or Mass*sin(i) [Jupiter Mass]
# COLUMN pl_bmassjerr1:  Planet Mass or Mass*sin(i) [Jupiter Mass] Upper Unc.
# COLUMN pl_bmassjerr2:  Planet Mass or Mass*sin(i) [Jupiter Mass] Lower Unc.
# COLUMN pl_bmassjlim:   Planet Mass or Mass*sin(i) [Jupiter Mass] Limit Flag
# COLUMN pl_bmassprov:   Planet Mass or Mass*sin(i) Provenance
# COLUMN pl_orbeccen:    Eccentricity
# COLUMN pl_orbeccenerr1: Eccentricity Upper Unc.
# COLUMN pl_orbeccenerr2: Eccentricity Lower Unc.
# COLUMN pl_orbeccenlim: Eccentricity Limit Flag
# COLUMN pl_insol:       Insolation Flux [Earth Flux]
# COLUMN pl_insolerr1:   Insolation Flux Upper Unc. [Earth Flux]
# COLUMN pl_insolerr2:   Insolation Flux Lower Unc. [Earth Flux]
# COLUMN pl_insollim:    Insolation Flux Limit Flag
# COLUMN pl_eqt:         Equilibrium Temperature [K]
# COLUMN pl_eqterr1:     Equilibrium Temperature Upper Unc. [K]
# COLUMN pl_eqterr2:     Equilibrium Temperature Lower Unc. [K]
# COLUMN pl_eqtlim:      Equilibrium Temperature Limit Flag
# COLUMN ttv_flag:       Data show Transit Timing Variations
# COLUMN st_refname:     Stellar Parameter Reference
# COLUMN st_spectype:    Spectral Type
# COLUMN st_teff:        Stellar Effective Temperature [K]
# COLUMN st_tefferr1:    Stellar Effective Temperature Upper Unc. [K]
# COLUMN st_tefferr2:    Stellar Effective Temperature Lower Unc. [K]
# COLUMN st_tefflim:     Stellar Effective Temperature Limit Flag
# COLUMN st_rad:         Stellar Radius [Solar Radius]
# COLUMN st_raderr1:     Stellar Radius Upper Unc. [Solar Radius]
# COLUMN st_raderr2:     Stellar Radius Lower Unc. [Solar Radius]
# COLUMN st_radlim:      Stellar Radius Limit Flag
# COLUMN st_mass:        Stellar Mass [Solar mass]
# COLUMN st_masserr1:    Stellar Mass Upper Unc. [Solar mass]
# COLUMN st_masserr2:    Stellar Mass Lower Unc. [Solar mass]
# COLUMN st_masslim:     Stellar Mass Limit Flag
# COLUMN st_met:         Stellar Metallicity [dex]
# COLUMN st_meterr1:     Stellar Metallicity Upper Unc. [dex]
# COLUMN st_meterr2:     Stellar Metallicity Lower Unc. [dex]
# COLUMN st_metlim:      Stellar Metallicity Limit Flag
# COLUMN st_metratio:    Stellar Metallicity Ratio
# COLUMN st_logg:        Stellar Surface Gravity [log10(cm/s**2)]
# COLUMN st_loggerr1:    Stellar Surface Gravity Upper Unc. [log10(cm/s**2)]
# COLUMN st_loggerr2:    Stellar Surface Gravity Lower Unc. [log10(cm/s**2)]
# COLUMN st_logglim:     Stellar Surface Gravity Limit Flag
# COLUMN sy_refname:     System Parameter Reference
# COLUMN rastr:          RA [sexagesimal]
# COLUMN ra:             RA [deg]
# COLUMN decstr:         Dec [sexagesimal]
# COLUMN dec:            Dec [deg]
# COLUMN sy_dist:        Distance [pc]
# COLUMN sy_disterr1:    Distance [pc] Upper Unc
# COLUMN sy_disterr2:    Distance [pc] Lower Unc
# COLUMN sy_vmag:        V (Johnson) Magnitude
# COLUMN sy_vmagerr1:    V (Johnson) Magnitude Upper Unc
# COLUMN sy_vmagerr2:    V (Johnson) Magnitude Lower Unc
# COLUMN sy_kmag:        Ks (2MASS) Magnitude
# COLUMN sy_kmagerr1:    Ks (2MASS) Magnitude Upper Unc
# COLUMN sy_kmagerr2:    Ks (2MASS) Magnitude Lower Unc
# COLUMN sy_gaiamag:     Gaia Magnitude
# COLUMN sy_gaiamagerr1: Gaia Magnitude Upper Unc
# COLUMN sy_gaiamagerr2: Gaia Magnitude Lower Unc
# COLUMN rowupdate:      Date of Last Update
# COLUMN pl_pubdate:     Planetary Parameter Reference Publication Date
# COLUMN releasedate:    Release Date

In [6]:
import pandas as pd

planets = pd.read_csv(r'C:\Users\FLopezP\Desktop\PCIC\Tercer Semestre\exoplanets.csv', on_bad_lines = 'skip')
planets.head()

pl_name hostname  default_flag  sy_snum  sy_pnum  discoverymethod  \
0  11 Com b   11 Com             1        2        1  Radial Velocity   
1  11 Com b   11 Com             0        2        1  Radial Velocity   
2  11 Com b   11 Com             0        2        1  Radial Velocity   
3  11 UMi b   11 UMi             0        1        1  Radial Velocity   
4  11 UMi b   11 UMi             1        1        1  Radial Velocity   

   disc_year                           disc_facility              soltype  \
0       2007                        Xinglong Station  Published Confirmed   
1       2007                        Xinglong Station  Published Confirmed   
2       2007                        Xinglong Station  Published Confirmed   
3       2009  Thueringer Landessternwarte Tautenburg  Published Confirmed   
4       2009  Thueringer Landessternwarte Tautenburg  Published Confirmed   

   pl_controv_flag  ... sy_vmagerr2  sy_kmag  sy_kmagerr1  sy_kmagerr2  \
0                0  ...      -0.023    2.282        0.346       -0.346   
1                0  ...      -0.023    2.282        0.346       -0.346   
2                0  ...      -0.023    2.282        0.346       -0.346   
3                0  ...      -0.005    1.939        0.270       -0.270   
4                0  ...      -0.005    1.939        0.270       -0.270   

   sy_gaiamag  sy_gaiamagerr1  sy_gaiamagerr2   rowupdate  pl_pubdate  \
0     4.44038        0.003848       -0.003848  2023-09-19     2023-08   
1     4.44038        0.003848       -0.003848  2014-05-14     2008-01   
2     4.44038        0.003848       -0.003848  2014-07-23     2011-08   
3     4.56216        0.003903       -0.003903  2018-04-25     2009-10   
4     4.56216        0.003903       -0.003903  2018-09-04     2017-03   

   releasedate  
0   2023-09-19  
1   2014-05-14  
2   2014-07-23  
3   2014-05-14  
4   2018-09-06  

[5 rows x 92 columns]

In [33]:
# K vergas hacemos con esto??
for i in range(25):
    print(planets.iloc[i]['st_metratio'])

[Fe/H]
[Fe/H]
nan
[Fe/H]
[Fe/H]
nan
nan
[Fe/H]
[Fe/H]
nan
nan
[Fe/H]
[Fe/H]
[M/H]
[Fe/H]
nan
[Fe/H]
[Fe/H]
[Fe/H]
[M/H]
[Fe/H]
[Fe/H]
nan
[Fe/H]
nan


In [23]:
import numpy as np
dropped_index = []
for i in range(len(planets)):
    if np.isnan(planets.iloc[i]['pl_orbper']) or np.isnan(planets.iloc[i]['pl_rade']) or np.isnan(planets.iloc[i]['pl_orbeccen']) or np.isnan(planets.iloc[i]['pl_eqt']) or np.isnan(planets.iloc[i]['st_mass']) or np.isnan(planets.iloc[i]['sy_dist']):
        dropped_index.append(i)
    if type(planets.iloc[i]['st_metratio']) == float:
        dropped_index.append(i)

new_planets = planets.drop(dropped_index)
new_planets = new_planets.reset_index()
new_planets = new_planets.drop(columns = 'index')
new_planets.head()

pl_name      hostname  default_flag  sy_snum  sy_pnum  \
0      55 Cnc e        55 Cnc             0        2        7   
1      AU Mic b        AU Mic             1        1        4   
2      AU Mic c        AU Mic             1        1        4   
3   BD+20 594 b     BD+20 594             0        1        1   
4  BD-14 3065 b  BD-14 3065 A             1        3        1   

   discoverymethod  disc_year                                 disc_facility  \
0  Radial Velocity       2004                          McDonald Observatory   
1          Transit       2020  Transiting Exoplanet Survey Satellite (TESS)   
2          Transit       2021  Transiting Exoplanet Survey Satellite (TESS)   
3          Transit       2016                                            K2   
4          Transit       2024  Transiting Exoplanet Survey Satellite (TESS)   

               soltype  pl_controv_flag  ... sy_vmagerr2  sy_kmag  \
0  Published Confirmed                0  ...      -0.023    4.015   
1  Published Confirmed                0  ...      -0.100    4.529   
2  Published Confirmed                0  ...      -0.100    4.529   
3  Published Confirmed                0  ...      -0.012    9.368   
4  Published Confirmed                0  ...      -0.013    9.932   

   sy_kmagerr1  sy_kmagerr2  sy_gaiamag  sy_gaiamagerr1  sy_gaiamagerr2  \
0        0.036       -0.036     5.72973        0.000852       -0.000852   
1        0.020       -0.020     7.84038        0.000731       -0.000731   
2        0.020       -0.020     7.84038        0.000731       -0.000731   
3        0.018       -0.018    10.86440        0.000249       -0.000249   
4        0.026       -0.026    10.91000        0.001617       -0.001617   

    rowupdate  pl_pubdate  releasedate  
0  2021-02-05     2011-09   2015-12-03  
1  2024-09-28     2023-12   2024-09-28  
2  2024-09-28     2023-12   2024-09-28  
3  2018-04-25     2016-10   2016-07-28  
4  2024-06-25     2024-03   2024-06-25  

[5 rows x 92 columns]

In [25]:
period, radius, excen, temp, mass, grav, dist = [], [], [], [], [], [], []
for i in range(len(new_planets)):
    a = new_planets.iloc[i]
    period.append(a['pl_orbper'])
    radius.append(a['pl_rade'])
    excen.append(a['pl_orbeccen'])
    temp.append(a['pl_eqt'])
    mass.append(a['st_mass'])
    grav.append(a['st_metratio'])
    dist.append(a['sy_dist'])

In [31]:
print(period[:5])
print(radius[:5])
print(excen[:5])
print(temp[:5])
print(mass[:5])
print(grav[:5])
print(dist[:5])

[0.7365437, 8.46308, 18.85969, 41.6855, 4.2889731]
[2.08, 3.95677019, 2.52202066, 2.23, 21.59]
[0.061, 0.00577, 0.00338, 0.0, 0.066]
[1958.0, 600.0, 459.0, 546.0, 2001.0]
[0.905, 0.51, 0.51, 0.961, 1.41]
['[Fe/H]', '[Fe/H]', '[Fe/H]', '[Fe/H]', '[Fe/H]']
[12.5855, 9.7221, 9.7221, 179.461, 589.423]


In [37]:
from sklearn.preprocessing import StandardScaler

# HACER QUE QUEDE ENTRE (0,1)
full_list = [period, radius, excen, temp, mass, dist]
for _ in full_list:
    a = StandardScaler()
    array = np.array(_)
    array = array.reshape(-1, 1)
    aux = a.fit_transform(array)
    print(aux)

[[-0.3978224 ]
 [-0.2783062 ]
 [-0.11748856]
 ...
 [-0.36491211]
 [-0.31225504]
 [-0.31226185]]
[[-0.04495987]
 [-0.02624107]
 [-0.04055118]
 ...
 [ 0.08779292]
 [-0.04515935]
 [-0.04533888]]
[[ 0.88511129]
 [-0.09613789]
 [-0.13860006]
 ...
 [ 0.47647955]
 [-0.19865116]
 [-0.19865116]]
[[ 2.68423052]
 [-0.64843997]
 [-0.99446835]
 ...
 [ 2.15659859]
 [ 0.69395381]
 [ 0.74990734]]
[[-0.14083249]
 [-1.90191519]
 [-1.90191519]
 ...
 [ 2.08838612]
 [ 0.37188779]
 [ 0.70181215]]
[[-1.59924627]
 [-1.60539343]
 [-1.60539343]
 ...
 [-1.12359305]
 [-1.58704234]
 [-1.58704234]]
